FROM oznu/homebridge:raspberry-pi

# Enable systemd init system in container
ENV INITSYSTEM on

RUN install_packages libnss-mdns

COPY config.json /homebridge/config.json
COPY package.json /homebridge/package.json

# Expose port
EXPOSE 5353 51826
