FROM oznu/homebridge:raspberry-pi

# Enable systemd init system in container
ENV INITSYSTEM on

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

COPY config.json /homebridge/config.json
COPY package.json /homebridge/package.json

# Expose port
EXPOSE 5353 51826
