FROM balenalib/%%BALENA_MACHINE_NAME%%-python

RUN apt-get update && apt-get install -yq \
   build-essential && \
   apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY doorbell_sub.py ./

CMD ["python", "doorbell_sub.py"]
