FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY doorbell_sub.py ./

CMD ["python", "doorbell_sub.py"]
